version: '3'

services:

  raspberrypi:
    build: ./docker/raspberrypi/
    restart: unless-stopped
    volumes:
      - ./bin:/app/bin
      - ./data:/app/data

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    restart: unless-stopped
    volumes:
      - .:/var/www/html